import { ProductsPage } from '@/components/products/products-page'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sản phẩm - Zent',
  description: 'Khám phá bộ sưu tập thời trang nam tối giản, chất lượng cao từ Zent',
}

// Mock data - replace with actual data fetching
const products = [
  {
    id: '1',
    name: 'Áo thun nam basic trắng',
    price: 299000,
    originalPrice: 399000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.5,
    reviewCount: 1234,
    inStock: true,
    freeShipping: true,
    category: 'ao-thun',
    badge: 'NEW',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Trắng', value: 'white', hex: '#FFFFFF' },
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Xám', value: 'gray', hex: '#9CA3AF' },
    ],
  },
  {
    id: '2',
    name: 'Áo polo nam cao cấp',
    price: 399000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.8,
    reviewCount: 856,
    inStock: true,
    freeShipping: true,
    category: 'ao-polo',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Xanh navy', value: 'navy', hex: '#1E3A8A' },
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Trắng', value: 'white', hex: '#FFFFFF' },
    ],
  },
  {
    id: '3',
    name: 'Quần jean nam slim fit',
    price: 599000,
    originalPrice: 799000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.6,
    reviewCount: 2341,
    inStock: true,
    freeShipping: true,
    category: 'quan',
    badge: 'HOT',
    sizes: ['29', '30', '31', '32', '33'],
    colors: [
      { name: 'Xanh đậm', value: 'dark-blue', hex: '#1E40AF' },
      { name: 'Đen', value: 'black', hex: '#000000' },
    ],
  },
  {
    id: '4',
    name: 'Áo sơ mi nam trắng',
    price: 449000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.7,
    reviewCount: 1567,
    inStock: true,
    freeShipping: true,
    category: 'ao-so-mi',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Trắng', value: 'white', hex: '#FFFFFF' },
      { name: 'Xanh nhạt', value: 'light-blue', hex: '#DBEAFE' },
    ],
  },
  {
    id: '5',
    name: 'Quần kaki nam',
    price: 499000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.5,
    reviewCount: 987,
    inStock: true,
    freeShipping: true,
    category: 'quan',
    sizes: ['29', '30', '31', '32', '33', '34'],
    colors: [
      { name: 'Be', value: 'beige', hex: '#D4C5B9' },
      { name: 'Xanh rêu', value: 'olive', hex: '#84A98C' },
      { name: 'Đen', value: 'black', hex: '#000000' },
    ],
  },
  {
    id: '6',
    name: 'Áo thun polo basic',
    price: 349000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.4,
    reviewCount: 654,
    inStock: true,
    freeShipping: true,
    category: 'ao-polo',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Trắng', value: 'white', hex: '#FFFFFF' },
      { name: 'Xám', value: 'gray', hex: '#9CA3AF' },
      { name: 'Xanh navy', value: 'navy', hex: '#1E3A8A' },
    ],
  },
  {
    id: '7',
    name: 'Quần short nam',
    price: 299000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.3,
    reviewCount: 432,
    inStock: false,
    freeShipping: false,
    category: 'quan',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Xanh navy', value: 'navy', hex: '#1E3A8A' },
      { name: 'Đen', value: 'black', hex: '#000000' },
    ],
  },
  {
    id: '8',
    name: 'Áo khoác bomber',
    price: 799000,
    originalPrice: 999000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.9,
    reviewCount: 3210,
    inStock: true,
    freeShipping: true,
    category: 'ao-khoac',
    badge: 'BEST SELLER',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Xanh rêu', value: 'olive', hex: '#84A98C' },
    ],
  },
  {
    id: '9',
    name: 'Áo thun nam đen',
    price: 299000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.6,
    reviewCount: 1890,
    inStock: true,
    freeShipping: true,
    category: 'ao-thun',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Trắng', value: 'white', hex: '#FFFFFF' },
      { name: 'Xám', value: 'gray', hex: '#9CA3AF' },
    ],
  },
  {
    id: '10',
    name: 'Quần jogger nam',
    price: 449000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.5,
    reviewCount: 756,
    inStock: true,
    freeShipping: true,
    category: 'quan',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Xám', value: 'gray', hex: '#9CA3AF' },
      { name: 'Xanh navy', value: 'navy', hex: '#1E3A8A' },
    ],
  },
  {
    id: '11',
    name: 'Áo hoodie nam',
    price: 599000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.7,
    reviewCount: 1234,
    inStock: true,
    freeShipping: true,
    category: 'ao-khoac',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Xám', value: 'gray', hex: '#9CA3AF' },
      { name: 'Xanh navy', value: 'navy', hex: '#1E3A8A' },
      { name: 'Be', value: 'beige', hex: '#D4C5B9' },
    ],
  },
  {
    id: '12',
    name: 'Áo thun nam xám',
    price: 299000,
    image: '/placeholder.svg',
    hoverImage: '/placeholder.svg',
    rating: 4.4,
    reviewCount: 890,
    inStock: true,
    freeShipping: true,
    category: 'ao-thun',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Xám', value: 'gray', hex: '#9CA3AF' },
      { name: 'Đen', value: 'black', hex: '#000000' },
      { name: 'Trắng', value: 'white', hex: '#FFFFFF' },
    ],
  },
]

const categories = [
  { id: 'all', name: 'Tất cả', slug: 'all' },
  { id: 'ao-thun', name: 'Áo thun', slug: 'ao-thun' },
  { id: 'ao-polo', name: 'Áo polo', slug: 'ao-polo' },
  { id: 'ao-so-mi', name: 'Áo sơ mi', slug: 'ao-so-mi' },
  { id: 'quan', name: 'Quần', slug: 'quan' },
  { id: 'ao-khoac', name: 'Áo khoác', slug: 'ao-khoac' },
]

export default function Page() {
  return <ProductsPage products={products} categories={categories} />
}
